version: '3.7'

services:
  app:
    build: .
    ports:
      - 8084:8080
    command: sh -c 'yarn && yarn serve'
    volumes:
      - .:/app
      - ~/.gitconfig:/etc/gitconfig
    working_dir: /app
